#!/usr/bin/env python3

import rospy
import rospkg
from std_msgs.msg import Int32
from time import *

rospy.init_node("asdasd")
pub = rospy.Publisher("asdasd", Int32, queue_size=1)
rate = rospy.Rate(1)

count = 0
while not rospy.is_shutdown():
    # sleep(1)
    pub.publish(count)
    print("asdasd")

    count += 1
    # rate.sleep()
    # if count == 2:
    #     break
